<?php

namespace Proxies\__CG__\AL\GsbBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \AL\GsbBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'login', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'pass', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'fonction', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'codePostal', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'ville', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'dateEmbauche', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'fichesFrais');
        }

        return array('__isInitialized__', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'login', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'pass', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'fonction', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'codePostal', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'ville', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'dateEmbauche', '' . "\0" . 'AL\\GsbBundle\\Entity\\Utilisateur' . "\0" . 'fichesFrais');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPass($pass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPass', array($pass));

        return parent::setPass($pass);
    }

    /**
     * {@inheritDoc}
     */
    public function getPass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPass', array());

        return parent::getPass();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonction($fonction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonction', array($fonction));

        return parent::setFonction($fonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonction', array());

        return parent::getFonction();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEmbauche($dateEmbauche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEmbauche', array($dateEmbauche));

        return parent::setDateEmbauche($dateEmbauche);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEmbauche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEmbauche', array());

        return parent::getDateEmbauche();
    }

    /**
     * {@inheritDoc}
     */
    public function addFichesFrai(\AL\GsbBundle\Entity\FicheFrais $fichesFrais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFichesFrai', array($fichesFrais));

        return parent::addFichesFrai($fichesFrais);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFichesFrai(\AL\GsbBundle\Entity\FicheFrais $fichesFrais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFichesFrai', array($fichesFrais));

        return parent::removeFichesFrai($fichesFrais);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichesFrais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichesFrais', array());

        return parent::getFichesFrais();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
