<?php

namespace Proxies\__CG__\AL\GsbBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheFrais extends \AL\GsbBundle\Entity\FicheFrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'dateRedac', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'nbJustificatifs', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'utilisateur', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'lignesFraisForfait', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'lignesFraisHorsForfait');
        }

        return array('__isInitialized__', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'dateRedac', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'nbJustificatifs', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'utilisateur', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'lignesFraisForfait', '' . "\0" . 'AL\\GsbBundle\\Entity\\FicheFrais' . "\0" . 'lignesFraisHorsForfait');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheFrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRedac($dateRedac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRedac', array($dateRedac));

        return parent::setDateRedac($dateRedac);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRedac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRedac', array());

        return parent::getDateRedac();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatifs($nbJustificatifs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatifs', array($nbJustificatifs));

        return parent::setNbJustificatifs($nbJustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatifs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatifs', array());

        return parent::getNbJustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide($montantValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', array($montantValide));

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', array());

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', array($dateModif));

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', array());

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(\AL\GsbBundle\Entity\Etat $etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(\AL\GsbBundle\Entity\Utilisateur $utilisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', array($utilisateur));

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', array());

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function addLignesFraisForfait(\AL\GsbBundle\Entity\LigneFraisForfait $lignesFraisForfait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLignesFraisForfait', array($lignesFraisForfait));

        return parent::addLignesFraisForfait($lignesFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLignesFraisForfait(\AL\GsbBundle\Entity\LigneFraisForfait $lignesFraisForfait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLignesFraisForfait', array($lignesFraisForfait));

        return parent::removeLignesFraisForfait($lignesFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function getLignesFraisForfait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLignesFraisForfait', array());

        return parent::getLignesFraisForfait();
    }

    /**
     * {@inheritDoc}
     */
    public function addLignesFraisHorsForfait(\AL\GsbBundle\Entity\LigneFraisHorsForfait $lignesFraisHorsForfait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLignesFraisHorsForfait', array($lignesFraisHorsForfait));

        return parent::addLignesFraisHorsForfait($lignesFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLignesFraisHorsForfait(\AL\GsbBundle\Entity\LigneFraisHorsForfait $lignesFraisHorsForfait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLignesFraisHorsForfait', array($lignesFraisHorsForfait));

        return parent::removeLignesFraisHorsForfait($lignesFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function getLignesFraisHorsForfait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLignesFraisHorsForfait', array());

        return parent::getLignesFraisHorsForfait();
    }

}
